main:
  - name: "Summary"
    url: "/"
    weight: 1

  - name: "Publications"
    url: "/publication/"
    weight: 2

  - name: "Bio"
    url: "/authors/admin/"
    weight: 3

  - name: "News"
    url: "/news/"
    weight: 4

  - name: "Projects"
    url: "/project/"
    weight: 5
