main:
  - name: "Main"
    url: "/"
    weight: 1

  - name: "News"
    url: "/news/"
    weight: 2

  - name: "Publications"
    url: "/publications/"
    weight: 3

  - name: "Talks"
    url: "/talk/"
    weight: 4

  - name: "Bio"
    url: "/authors/admin/"
    weight: 5
