main:
  - name: "Summary"
    url: "/"
    weight: 1

  - name: "Publications"
    url: "/publications/"
    weight: 2

  - name: "Bio"
    url: "/bio/"
    weight: 3

  - name: "Talks"
    url: "/talk/"
    weight: 4
